version: 2.1

jobs:
  unit-test:
    docker:
      - image: circleci/node:12
    environment:
      NODE_ENV: test
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm i
      - run:
          name: Run tests
          command: CI=true npm t
  build-job:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm i
      - run:
          name: Build source
          command: npm run build

workflows:
  version: 2
  testing:
    jobs:
      - unit-test
    filters:
      branches:
        ignore:
          - master
  build:
    jobs:
      - build-job
    filters:
      branches:
        only:
          - master